name: elevator
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  go_router: any
  flutter_svg: ^2.0.17
  rxdart: ^0.27.2
  intl_phone_field: ^3.2.0
  country_code_picker: ^3.3.0
  retrofit: ^4.7.1
  analyzer: any
  dio: ^5.9.0
  json_serializable: any
  json_annotation: ^4.9.0
  retrofit_generator: ^9.1.5
  build_runner: ^2.4.14
  dartz: ^0.10.1
  internet_connection_checker: ^3.0.1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  bottom_picker: ^4.1.1
  flutter_otp_text_field: ^1.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
      - family: Tajawal
        fonts:
          - asset: assets/fonts/Tajawal-Light.ttf
            weight: 300
          - asset: assets/fonts/Tajawal-Regular.ttf
            weight: 400
          - asset: assets/fonts/Tajawal-Medium.ttf
            weight: 500
          - asset: assets/fonts/Tajawal-ExtraLight.ttf
            weight: 600
          - asset: assets/fonts/Tajawal-Bold.ttf
            weight: 700