name: elevator
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  go_router: any
  flutter_svg: ^2.0.17
  rxdart: ^0.27.2
  intl_phone_field: ^3.2.0
  dio: ^5.7.0
  dartz: ^0.10.1
  internet_connection_checker: ^3.0.1
  pretty_dio_logger: ^1.4.0
  flutter_otp_text_field: ^1.5.1+1
  dotted_border: ^3.1.0
  table_calendar: ^3.2.0
  dropdown_overlay: ^0.1.0
  image_picker: ^1.2.0
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  syncfusion_flutter_pdfviewer: ^31.1.20
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  device_info_plus: ^12.2.0
  open_filex: ^4.7.0
  url_launcher: ^6.3.2
  get_it: ^8.2.0
  lottie: ^3.3.2
  flutter_secure_storage: ^9.2.4
  timeline_tile: ^2.0.0
  easy_localization: ^3.0.8
  flutter_phoenix: ^1.1.1
  flutter_dotenv: ^6.0.0
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.14
  json_serializable: any
  json_annotation: ^4.9.0
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  retrofit_generator: ^9.1.5
  analyzer: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/appLogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/pdfs/
    - assets/json/
    - assets/translations/
    - .env

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 600
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700